name: Create UMR-Release

on:
  push:
    branches: main
    paths: 
      - "02-dockerfiles/**.Dockerfile"
      - "!02-dockerfiles/**_devel.Dockerfile"
  workflow_dispatch:
    inputs: 
      tag_suffix:
        description: 'Tag suffix'
        default: 0
        required: true 
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version from date
        id: tag_id
        run: |
          VAR="${{ github.event.inputs.tag_suffix }}"
          if [[ ${VAR} == "" || ${VAR} == "0" ]]; then
            CTAG="$(date '+%Y.%m.%d')"
          else
            CTAG="$(date '+%Y.%m.%d')-${VAR}"
          fi
          echo ::set-output name=ctag::"${CTAG}"
          echo "${CTAG}"
      - name: Set prerelease name
        id: release_id
        run: |
          echo ::set-output name=releasename::"v${{ steps.tag_id.outputs.ctag }} (UMR/RSTUDIO/SSH/SHINY)"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          custom_tag: ${{ steps.tag_id.outputs.ctag }}
          tag_prefix: "v"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.release_id.outputs.releasename }}
          generateReleaseNotes: true
          allowUpdates: false
          token: ${{ secrets.GITHUB_TOKEN }}
