name: Weekly Actions

on:
  schedule:
    - cron: "0 12 * * SUN"
  push:
    branches: main
    paths:
      - "assets/**"
      - "build/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-devel:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install distro-info-data
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rversions
            any::jsonlite
            any::httr2
            any::yaml
            any::data.table
      - name: Make changes to pull request
        run: |
          rm -rf 02-dockerfiles 03-compose 04-bakefiles
          Rscript ./build/build.R umr1283,${GITHUB_REPOSITORY_OWNER} bullseye
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker images
        run: docker-compose -f 03-compose/devel.yml build
      - name: Push Docker images
        run: docker-compose -f 03-compose/devel.yml push
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "ci: automatic weekly build update"
          signoff: false
          branch: weekly-build-updates
          delete-branch: true
          title: "Automatic weekly build update"
  check-devel:
    runs-on: ubuntu-latest
    if: ${{ true }}
    needs: build-devel
    strategy:
      fail-fast: false
      matrix:
        image-ref: [r-ver, umr1283, rstudio, ssh, shiny]
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/umr1283/${{ matrix.image-ref }}:devel"
          output: "trivy-${{ matrix.image-ref }}-devel.sarif"
          format: "sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-${{ matrix.image-ref }}-devel.sarif"
